
spring:
  profiles:
    activce:
        -dev
---

spring:
  profiles: test
  application:
    name: springcloud-provider-user-test

server:
  port: 8002
    
eureka: 
  instance:
    instance-id: springcloud-provider-user-8002-test
    prefer-ip-address: true    
   
        
---

spring: 
  profiles: release
  application:
    name: springcloud-provider-user

server:
  port: 8002

eureka: 
  instance:
    instance-id: springcloud-provider-user-8002
    prefer-ip-address: true    
    
