spring:
  profiles:
    activce:
        -dev
---

spring:
  profiles: dev
  application:
    name: springcloud-provider-user-8001-dev
    
server:
  port: 8001

eureka:
  client:
    serviceUrl:
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-user-8001
    prefer-ip-address: true

info:
  app.name: springcloud-provider-user-8001
  company.name: com.wpx
  build.artifactId: $project.artifactId$
  build.version: $project.version$

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
---

spring:
  profiles: test
  application:
    name: springcloud-provider-user-8001-test
    
server:
  port: 8001

eureka:
  client:
    serviceUrl:
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-user-8001
    prefer-ip-address: true

info:
  app.name: springcloud-provider-user-8001
  company.name: com.wpx
  build.artifactId: $project.artifactId$
  build.version: $project.version$

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
# 请保存为UTF-8格式