
spring:
  profiles:
    activce:
        -dev
---

spring:
  profiles: test
  application:
    name: springcloud-provider-user-test
    
testVal: 118
    
---

spring: 
  profiles: release
  application:
    name: springcloud-provider-user
    
testVal: 118