spring:
  profiles:
    activce:
        -dev
---

spring:
  profiles: test
  application:
    name: springcloud-provider-user-test  
  zipkin:
    base-url: http://localhost:9411
    
testVal: 666
    
---

spring: 
  profiles: release
  application:
    name: springcloud-provider-user
  zipkin:
    base-url: http://localhost:9411
    
#负载均衡策略配置
springcloud-provider-student:
  ribbon:
    NFLoadBalancerRuleClassName: com.wpx.myrule.StudentRule
springcloud-provider-teacher:
  ribbon:
    NFLoadBalancerRuleClassName: com.wpx.myrule.TeacherRule
    
testVal: 666