spring:
  profiles:
    activce:
        -dev
---

spring:
  profiles: test  
  application:
    name: springcloud-eureka-7001-test
    
server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---

spring:
  profiles: release
  application:
    name: springcloud-eureka-7001

server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      
# 请保存为UTF-8格式