
spring:
  profiles:
    activce:
        -dev
---

spring:
  profiles: test
  application:
    name: springcloud-provider-user-8001-test
    
server:
  port: 8001

        
---

spring: 
  profiles: release
  application:
    name: springcloud-provider-user-8001
    
server:
  port: 8001

