spring:
  profiles:
    activce:
        -dev
---

spring:
  profiles: test
  application:
    name: springcloud-provider-student-test  
  zipkin:
    base-url: http://localhost:9411
    
testVal: 666
    
---

spring: 
  profiles: release
  application:
    name: springcloud-provider-student
  zipkin:
    base-url: http://localhost:9411
    
testVal: 666