
spring:
  profiles:
    activce:
        -dev
---

spring:
  profiles: test
  application:
    name: springcloud-provider-user-8001-test
    
server:
  port: 8001

info:
  app:
   name: springcloud-provider-user-8001-test
  company:
   name: com.wpx
  build:
   artifactId: $project.artifactId$
   version: $project.version$
        
---

spring: 
  profiles: release
  application:
    name: springcloud-provider-user-8001
    
server:
  port: 8001

info:
  app:
   name: springcloud-provider-user-8001
  company:
   name: com.wpx
  build:
   artifactId: $project.artifactId$
   version: $project.version$