spring:
  profiles:
    activce:
        -dev
---

spring:
  profiles: test  
  application:
    name: springcloud-eureka-7002-test
    
server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
---

spring:
  profiles: release
  application:
    name: springcloud-eureka-7002

server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/
      
# 请保存为UTF-8格式