
spring:
  profiles:
    activce:
        -dev
---

spring:
  profiles: test
  application:
    name: springcloud-provider-user-test
 
eureka: 
  instance:
    instance-id: springcloud-provider-user-8001-test
    prefer-ip-address: true
    
server:
  port: 8001
        
---

spring: 
  profiles: release
  application:
    name: springcloud-provider-user
    
eureka: 
  instance:
    instance-id: springcloud-provider-user-8001
    prefer-ip-address: true
    
server:
  port: 8001
