
spring:
  profiles:
    activce:
        -dev
---

spring:
  profiles: test
  application:
    name: springcloud-provider-user-test
    
server:
  port: 8006
          
---

spring: 
  profiles: release
  application:
    name: springcloud-provider-user
    
server:
  port: 8001