spring:
  profiles:
    activce:
        -dev
---

spring:
  profiles: dev  
  application:
    name:springcloud-config-dev
    
server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

---
spring:
  profiles: pro
  application:
    name:springcloud-config-pro

server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      
# 请保存为UTF-8格式