spring:
  profiles:
    activce:
        -dev
---

spring:
  profiles: test
  application:
    name: springcloud-provider-student-test  
  zipkin:
    sender:
      type: web  
    base-url: http://localhost:9411
    
testVal: 8004-test
    
---

spring: 
  profiles: release
  application:
    name: springcloud-provider-student
  zipkin:
    sender:
      type: web
    base-url: http://localhost:9411
    
testVal: 8004