
spring:
  profiles:
    activce:
        -dev
---

spring:
  profiles: test
  application:
    name: springcloud-provider-user-test
  rabbitmq:
   host: localhost
   port: 5672
   username: guest
   password: guest
  cloud:
   bus:
    enabled: true
    trace:
     enabled: true  
    
server:
  port: 8009
          
---

spring: 
  profiles: release
  application:
    name: springcloud-provider-user
  rabbitmq:
   host: localhost
   port: 5672
   username: guest
   password: guest
  cloud:
   bus:
    enabled: true
    trace:
     enabled: true
    
server:
  port: 8001